### ISSUE TITLE
Rails 3.1

### ISSUE THREAD

**Issue by kedano** [jeremyw/swish#4]
Anyone able to get it working on Rails 3.1? It gives multiple errors with activesupport-3.1.0.rc6

**Comment by jeremyw** [comment]
I don't know of anyone using swish with Rails 3.1. Pull requests are welcome -- otherwise I'll take a look when I get a chance.

**Comment by semanticart** [comment]
I'll go ahead and take a look at this in the next day or so.

**Comment by semanticart** [comment]
@KDN, I can't repro this.  I created a new rails 3.1.0rc6 app and added a controller with a method that just pulls a shot and dumps out the inspection of it.  It seems to work fine.

You can view the app here:  https://github.com/semanticart/rswish

Once you run it locally, visit http://localhost:3000/drbbl

When i do that, i see

```
#, @width=400, @image_url="http://dribbble.com/system/users/1/screenshots/21603/shot_1274474082.png?1309019706", @created_at=Fri May 21 16:34:42 -0400 2010, @views_count=3417, @id=21603, @url="http://dribbble.com/shots/21603-Moon", @rebounds_count=0, @height=300>
```

Let me know if you encounter any errors.  If you don't, try replying with the stack traces you see in your own app.

**Comment by kedano** [comment]
It looks like adding the httparty gem did the trick for me together with re-generating the project with RC6.

Is the gem dependent upon httparty?

**Comment by semanticart** [comment]
It is indeed. That's definitely in the gemspec so I'm not sure what's up. Glad you got it working!
